Traceback (most recent call last):
  File "/home/group4/Desktop/dht_test/myenv/finalmaincode.py", line 239, in <module>
    sensor1.exit()
  File "/home/group4/Desktop/dht_test/myenv/lib/python3.11/site-packages/adafruit_dht.py", line 92, in exit
    self.pulse_in.deinit()
  File "/home/group4/Desktop/dht_test/myenv/lib/python3.11/site-packages/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py", line 120, in deinit
    procs.remove(self._process)
ValueError: list.remove(x): x not in list
